//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanYonetim {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SunucuBilgi : global::System.Configuration.ApplicationSettingsBase {
        
        private static SunucuBilgi defaultInstance = ((SunucuBilgi)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SunucuBilgi())));
        
        public static SunucuBilgi Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sunucu {
            get {
                return ((string)(this["Sunucu"]));
            }
            set {
                this["Sunucu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VeriTabani {
            get {
                return ((string)(this["VeriTabani"]));
            }
            set {
                this["VeriTabani"] = value;
            }
        }
    }
}
